services:
  - type: web
    name: image-unmasking
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --threads 4 --timeout 120 --bind 0.0.0.0:$PORT proj:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: SIGHTENGINE_API_USER
        sync: false
      - key: SIGHTENGINE_API_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
